# Generated by Django 4.2 on 2023-04-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_emailtable_status_extrafiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraFiles',
            new_name='ExtraFile',
        ),
        migrations.AlterField(
            model_name='emailtable',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('recipients_created', 'Recipients Created'), ('mailing_in_progress', 'Mailing In Progress'), ('finished', 'Finished')], default='uploaded', verbose_name='Статус'),
        ),
    ]
