# Generated by Django 4.2 on 2023-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_extrafile_table_alter_emailtable_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtable',
            name='sendings',
            field=models.IntegerField(default=0, verbose_name='Отправки'),
        ),
        migrations.AlterField(
            model_name='emailtable',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('recipients_created', 'Recipients Created'), ('mailing_in_progress', 'Mailing In Progress'), ('finished', 'Finished')], default='uploaded', verbose_name='Статус'),
        ),
    ]
